ARG ROS_DISTRO=humble

FROM docker.io/hakuturu583/cuda_ros:humble-cuda-12.2.0-devel as build_stage

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    python3-vcstool git python3-colcon-common-extensions python3-rosdep \
    python3-bloom fakeroot \
    debhelper git gpg dh-python reprepro \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENTRYPOINT [ "/bin/bash" ]