#!/bin/bash

set -e

docker run --rm -v $PWD/src:/ws/src -v $PWD/xbuild:/ws/build \
          -v $PWD/xinstall:/ws/install -w /ws \
          -e ORIG_UID=$(id -u) -e ORIG_GID=$(id -g) \
          ghcr.io/fortefibre/buildroot:$ROS_DISTRO-aarch64 \
          "$@"