name: Create ROS debian packages

inputs:
  rosdistro:
    description: "ROS distro"
    default: "humble"
    required: true
  platform:
    description: "Platform (amd64 or aarch64)"
    default: "amd64"
  out_dir:
    description: "Packages output directory"
    default: "./deb"

runs:
  using: docker
  image: ghcr.io/fortefibre/buildroot:${{ inputs.rosdistro }}-${{ inputs.platform }}
  args:
    - deb
