name: Create ROS debian packages
description: Create ROS debian packages using Docker image

inputs:
  rosdistro:
    description: "ROS distro"
    default: "humble"
    required: true
  variant:
    description: Docker image variant. (small / small-cross / large / large-cross)
    default: "small"
  platform:
    description: "Platform (linux/amd64 or linux/arm64)"
    default: "linux/amd64"
  output_dir:
    description: "Packages output directory"
    default: "./deb"
  pre_script:
    description: "Bash script to execute before build"
    default: "echo OK"
runs:
  using: composite
  steps:
    - name: build
      run: |
        docker run --rm -v $PWD:/workspace -w /workspace -e INPUT_OUT_DIR -e INPUT_PRE_SCRIPT \
          --platform ${{ inputs.platform }} \
          ghcr.io/fortefibre/buildroot:${{ inputs.rosdistro }}-${{ inputs.variant }} deb
      env:
        INPUT_PRE_SCRIPT: ${{ inputs.pre_script }}
        INPUT_OUT_DIR: ${{ inputs.output_dir }}
      shell: bash
