name: Create ROS debian packages

inputs:
  rosdistro:
    description: "ROS distro"
    default: "humble"
    required: true
  platform:
    description: "Platform (amd64 or aarch64)"
    default: "amd64"
  out-dir:
    description: "Packages output directory"
    default: "./deb"

runs:
  using: composite
  steps:
    - name: Create debian packages
      run: |
        mkdir ${{ github.workspace }}/debs
        docker run --rm -v ${{ github.workspace }}:/ws -v $PWD/${{ inputs.out-dir }}:/debs \
           -v ${{ github.action_path }}/scripts:/scripts -w /ws \
           ghcr.io/fortefibre/buildroot:${{ inputs.rosdistro }}-${{ inputs.platform }} /scripts/build.bash
      shell: bash
