name: Upload apt repository to S3 bucket

inputs:
  input-dir:
    description: "Directory contains deb packages"
    required: true
  s3-bucket:
    description: "S3 bucket"
    required: true
  s3-access-key-id:
    description: "S3 access key id"
  s3-access-key-secret:
    description: "S3 access key secret"
  s3-endpoint:
    description: "S3 endpoint"
  gpg-private-key:
    description: "GPG private key to sign release file"
  gpg-fingerprint:
    description: "GPG fingerprint"

runs:
  using: "docker"
  image: docker://ghcr.io/fortefibre/deb-s3:latest
