name : update_apt_repo

inputs:
  token:
    description: 'GitHub token'
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        curl \
          -X POST \
          -H "Authorization: token ${{inputs.token}}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/ForteFibre/fortefibre_apt_repository/dispatches \
          -d "{\"event_type\":\"update-debs\",\"client_payload\":{\"repository\":\"${GITHUB_REPOSITORY}\"}}"
      shell: bash
      
