name: Upload apt repository to S3 bucket

inputs:
  input_dir:
    description: "Directory contains deb packages"
    required: true
  s3_bucket:
    description: "S3 bucket"
    required: true
  s3_access_key_id:
    description: "S3 access key id"
  s3_access_key_secret:
    description: "S3 access key secret"
  s3_endpoint:
    description: "S3 endpoint"
  gpg_private_key:
    description: "GPG private key to sign release file"
  gpg_fingerprint:
    description: "GPG fingerprint"
  codename:
    description: Ubuntu codename
    default: "jammy"

runs:
  using: "docker"
  image: docker://ghcr.io/fortefibre/deb-s3:latest
